#pragma once

// GLOBAL CLASS OR ENUMs
enum class ObjectType
{
	PORTAL = 55,
	MARIO = 0,
	SECRET_BRICK = 1,
	GOOMBA = 2,
	KOOPA = 3,
	PLATFORM = 4,
	BIGBOX = 5,
	FIRE_PIRANHA = 6,
	FIREBALL = 7,
	TAIL = 8,
	BRONZE_BRICK = 9,
	COIN = 10,
	NON_FIRE_PIRANHA = 12,
	SUPER_LEAF = 13,
	SUPER_MUSHROOM = 14,
	ICE_FLOWER = 15,
	P_SWITCH = 17,
};

enum class ObjectCategory
{
	PLAYER,
	ENEMY,
	MISC,
	ITEM,
	WEAPON,
	EFFECT,
	SCENE,
};

enum class PowerLevel
{
	TIER_0,
	TIER_1,
	TIER_2,
	TIER_3,
	TIER_4,
	TIER_5,
	TIER_6,
	TIER_7,
};

enum ItemOfBrick
{
	ITEM_RANDOM = 0,
	ITEM_MONEY = 1
};

enum BrickTransformation
{
	BRICK_TRANSFORM = 1,
	COIN_TRANSFORM = 2
};

enum TypeOfSecretBrick
{
	QUESTION_BRICK = 1,
	DISGUISED_BRONZE_BRICK = 2,
};

enum class OperationArea
{
	TOP_LEFT_FAR,
	TOP_LEFT_NEAR,
	TOP_RIGHT_FAR,
	TOP_RIGHT_NEAR,
	BOTTOM_LEFT_FAR,
	BOTTOM_LEFT_NEAR,
	BOTTOM_RIGHT_FAR,
	BOTTOM_RIGHT_NEAR,
	OUTSIDE_AREA,
};

enum TypeOfFirePiranha
{
	RED = 1,
	GREEN = 2,
};

enum class ItemOfBox
{
	STAR = 0,
	MUSHROOM = 1,
	FLOWER = 2,
	MAX_ITEM_TYPE_NUM,
};

// GLOBAL DEFINEs

#define ENEMY_STATE_ATTACKED_BY_TAIL			188  // lead to die or sleep
#define ENEMY_STATE_DIE_BY_WEAPON				199
#define ENEMY_STATE_MOVE						200
#define ENEMY_STATE_IDLE						201
#define ENEMY_DEFECT_SPEED_X_CAUSED_BY_TAIL		0.035f
#define ENEMY_DEFECT_SPEED_Y_CAUSED_BY_TAIL		0.28f

#define MARIO_GRAVITY				0.0006f

#define HIT_EFFECT_TIME	150
#define FIREBALL_BBOX_WIDTH		8
#define FIREBALL_BBOX_HEIGHT	8

#define ENEMY_STATE_DIE	199

#define	STATE_RAMMED				101
#define STATE_BEING_HIT_BY_TAIL		102

#define SPEED_X_TIER_1	0.125f
#define SPEED_X_TIER_2	0.140f
#define SPEED_X_TIER_3	0.155f
#define SPEED_X_TIER_4	0.170f
#define SPEED_X_TIER_5	0.190f
#define SPEED_X_TIER_6	0.210f
#define SPEED_X_TIER_7	0.230f

#define STATE_TRANSFORMATION	100
#define STATE_NORMAL			200
#define STATE_PRESSED				250

#define INITIAL_PLAYER_LIVES		4
#define START_POINT_X	32
#define START_POINT_Y	48
#define POINT_SIDE_LENGTH	4.0f

// Camera
#define CAMERA_INITIAL_Y		238.0f
#define CAMERA_HIDDEN_AREA_Y	464.0f

// Koopa
#define KOOPA_STATE_NORMAL					82
#define KOOPA_STATE_VIBRATE					83